# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Work\Organiser_Qt\organaiser_test.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tasks_list = QtWidgets.QListWidget(self.centralwidget)
        self.tasks_list.setObjectName("tasks_list")
        self.verticalLayout.addWidget(self.tasks_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_task_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(9)
        self.add_task_button.setFont(font)
        self.add_task_button.setObjectName("add_task_button")
        self.horizontalLayout.addWidget(self.add_task_button)
        self.delete_task_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(9)
        self.delete_task_button.setFont(font)
        self.delete_task_button.setObjectName("delete_task_button")
        self.horizontalLayout.addWidget(self.delete_task_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.schedule_table_1 = QtWidgets.QTableWidget(self.tab)
        #self.schedule_table_1.setEnabled(False)
        self.schedule_table_1.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.schedule_table_1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.schedule_table_1.setObjectName("schedule_table")
        self.schedule_table_1.setColumnCount(0)
        self.schedule_table_1.setRowCount(0)
        self.verticalLayout_5.addWidget(self.schedule_table_1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.schedule_table_2 = QtWidgets.QTableWidget(self.tab_2)
        self.schedule_table_2.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.schedule_table_2.setObjectName("schedule_table")
        self.schedule_table_2.setColumnCount(0)
        self.schedule_table_2.setRowCount(0)
        self.verticalLayout_6.addWidget(self.schedule_table_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.schedule_table_3 = QtWidgets.QTableWidget(self.tab_3)
        self.schedule_table_3.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.schedule_table_3.setObjectName("schedule_table")
        self.schedule_table_3.setColumnCount(0)
        self.schedule_table_3.setRowCount(0)
        self.verticalLayout_10.addWidget(self.schedule_table_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.schedule_table_4 = QtWidgets.QTableWidget(self.tab_4)
        self.schedule_table_4.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.schedule_table_4.setObjectName("schedule_table")
        self.schedule_table_4.setColumnCount(0)
        self.schedule_table_4.setRowCount(0)
        self.verticalLayout_9.addWidget(self.schedule_table_4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.schedule_table_5 = QtWidgets.QTableWidget(self.tab_5)
        self.schedule_table_5.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.schedule_table_5.setObjectName("schedule_table")
        self.schedule_table_5.setColumnCount(0)
        self.schedule_table_5.setRowCount(0)
        self.verticalLayout_8.addWidget(self.schedule_table_5)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.schedule_table_6 = QtWidgets.QTableWidget(self.tab_6)
        self.schedule_table_6.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.schedule_table_6.setObjectName("schedule_table")
        self.schedule_table_6.setColumnCount(0)
        self.schedule_table_6.setRowCount(0)
        self.verticalLayout_7.addWidget(self.schedule_table_6)
        self.tabWidget.addTab(self.tab_6, "")

        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.schedule_table_7 = QtWidgets.QTableWidget(self.tab_7)
        self.schedule_table_7.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.schedule_table_7.setObjectName("schedule_table_5")
        self.schedule_table_7.setColumnCount(0)
        self.schedule_table_7.setRowCount(0)
        self.verticalLayout_11.addWidget(self.schedule_table_7)
        self.tabWidget.addTab(self.tab_7, "")

        self.verticalLayout_2.addWidget(self.tabWidget)
        spacerItem = QtWidgets.QSpacerItem(340, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_3.addWidget(self.calendarWidget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.add_note_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(9)
        self.add_note_button.setFont(font)
        self.add_note_button.setObjectName("add_note_button")
        self.horizontalLayout_2.addWidget(self.add_note_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.notes_list = QtWidgets.QListWidget(self.centralwidget)
        self.notes_list.setObjectName("notes_list")
        self.verticalLayout_4.addWidget(self.notes_list)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.homework_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(9)
        self.homework_button.setFont(font)
        self.homework_button.setObjectName("homework_button")
        self.horizontalLayout_3.addWidget(self.homework_button)
        spacerItem2 = QtWidgets.QSpacerItem(650, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.connect_action = QtWidgets.QAction(MainWindow)
        self.connect_action.setObjectName("connect_action")
        self.sync_action = QtWidgets.QAction(MainWindow)
        self.sync_action.setObjectName("sync_action")
        self.exit_action = QtWidgets.QAction(MainWindow)
        self.exit_action.setObjectName("exit_action")
        self.help_action = QtWidgets.QAction(MainWindow)
        self.help_action.setObjectName("help_action")
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.menu.addAction(self.connect_action)
        self.menu.addAction(self.sync_action)
        self.menu.addSeparator()
        self.menu.addAction(self.exit_action)
        self.menu_2.addAction(self.help_action)
        self.menu_2.addAction(self.about_action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.centralwidget.setStyleSheet("MainStyle.qss")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Список задач"))
        self.add_task_button.setText(_translate("MainWindow", "Добавить задачу"))
        self.delete_task_button.setText(_translate("MainWindow", "Удалить выбранную"))
        self.label_2.setText(_translate("MainWindow", "Расписание занятий"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Понедельник"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Вторник"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Среда"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Четверг"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Пятница"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Суббота"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Воскресенье"))
        self.label_3.setText(_translate("MainWindow", "Заметки"))
        self.add_note_button.setText(_translate("MainWindow", "Добавить"))
        self.label_4.setText(_translate("MainWindow", "Дополнительно:"))
        self.homework_button.setText(_translate("MainWindow", "Домашнее задание"))
        self.menu.setTitle(_translate("MainWindow", "Подключение"))
        self.menu_2.setTitle(_translate("MainWindow", "Помощь"))
        self.connect_action.setText(_translate("MainWindow", "Подключиться к серверу"))
        self.sync_action.setText(_translate("MainWindow", "Синхронизировать"))
        self.exit_action.setText(_translate("MainWindow", "Выход"))
        self.help_action.setText(_translate("MainWindow", "Справка"))
        self.about_action.setText(_translate("MainWindow", "О программе"))
